server:
  port: 8763
  tomcat:
    max-threads: 2
    max-connections: 3
    accept-count: 1
spring:
  application:
    name: client2
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

