spring:
  profiles:
    active: development
  datasource:
    primary:
      url: jdbc:mysql://192.210.170.40:3306/oacy-project-house?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Sacrifice07@^
      driver-class-name: com.mysql.cj.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
      # ??????????????????????????????????????
      # ???????С????С?????
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # ????????????????????
      maxWait: 60000
      # ???ü????ò??????μ??????????????????????λ?????
      timeBetweenEvictionRunsMillis: 60000
      # ??????????????????С??????????λ?????
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # ??PSCache??????????????????PSCache???С
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # ???ü??????????filters????????????sql???????'wall'????????
      filters: stat,wall,slf4j
      # ???connectProperties????????mergeSql???????SQL???
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # ??????DruidDataSource????????
    #useGlobalDataSourceStat: true
    secondary:
      url: jdbc:h2:mem:test
      driver-class-name: org.h2.Driver
      schema: classpath:db/schema.sql
      data: classpath:db/data.sql
  thymeleaf:
    mode: HTML
    suffix: .html

---
spring:
  profiles: development
  thymeleaf:
    cache: false

---
spring:
  profiles: test
  datasource:
    primary:
      url: jdbc:h2:mem:test
      driver-class-name: org.h2.Driver
      schema: classpath:db/schema.sql
      data: classpath:db/data.sql

