server:
  port: 8080

spring:
  application:
    name: spring-cloud-newbie-user-web

eureka:
  client:
    register-with-eureka: true # 不向注册中心注册自己
    fetch-registry: true        # 是否检索服务
    service-url:
      defaultZone: http://localhost:9000/eureka/  # 注册中心访问地址