server:
  port: 9000

eureka:
  instance:
    hostname: localhost   # eureka 实例名称
  client:
    register-with-eureka: true # 不向注册中心注册自己
    fetch-registry: true       # 是否检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # 注册中心访问地址

spring:
  application:
    name: spring-cloud-newbie-server